# Generated by Django 4.2.1 on 2023-05-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_user', 'Admin User'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
