# Generated by Django 4.2.1 on 2023-05-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('Two wheeler', 'Two Wheeler'), ('Three wheeler', 'Three Wheeler'), ('Four wheeler', 'Four Wheeler')], max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_description', models.TextField()),
            ],
        ),
    ]
