# Generated by Django 4.2.1 on 2023-05-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Two wheeler', 'Two Wheeler'), ('Three wheeler', 'Three Wheeler'), ('Four wheeler', 'Four Wheeler')], max_length=100),
        ),
    ]
